CREATE TABLE IF NOT EXISTS reports (
  id SERIAL PRIMARY KEY,
  lat DOUBLE PRECISION NOT NULL,
  lon DOUBLE PRECISION NOT NULL,
  type VARCHAR(64),
  note TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_reports_lat_lon ON reports(lat, lon);
